Lesson 3
ElecTrOoD/django-geekshop pull request #3
Opened 2021-05-31 19:58 UTC by ElecTrOoD

2021-06-01 06:54 UTC, Vokler requested changes

2021-06-01 06:54 UTC, Vokler commented on products/views.py
>      context = {
Дополните так же context категориями

2021-06-01 07:59 UTC, ElecTrOoD commented on products/views.py
>      context = {
Дополнил context, в шаблоне сделал соответствующие изменения.
[https://github.com/ElecTrOoD/django-geekshop/commit/bcbc889fc6e5d38ed0b614ef19cedd538dfaa529](url)

2021-06-03 07:19 UTC, Vokler approved these changes

2021-06-03 07:19 UTC, merged